[theme]
primaryColor = "#667eea"
# backgroundColor and textColor removed to allow dynamic theme switching
# secondaryBackgroundColor removed to allow dynamic theme switching
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false